### ISSUE TITLE
Thumbnails not showing...

### ISSUE THREAD

**Issue by paulvonlux** [linuxmint/lmde-4-cinnamon-beta#8] opened 2020-02-25 15:59 UTC
Thumbnails of different images and videos not showing please use ffmpeg to auto generate them. FFMPEG has' them formats :) also it's free

**Comment by mtwebster** [comment] 2020-03-05 13:21
Can you provide more info - what program is not displaying thumnails?  Nemo?

`dpkg --list | grep ffmpeg`

ffmpeg's thumbnailer should already be in use - if you start nemo from a terminal, are there any errors? (Make sure to kill it first `nemo --quit` and then start it)

If your home folder a 'new' home folder (meaning, you didn't install this to a machine with a separate home partition)?

Try deleting the cache folder (`rm -rf ~/.cache`)

**Comment by clefebvre** [comment] 2020-03-05 16:20
I confirm that ffmpegthumbnailer is part of the default selection in LMDE 4. Closing because we can't reproduce.

**Closed as completed by clefebvre** 2020-03-05 16:20 UTC

**Comment by paulvonlux** [comment] 2020-03-06 17:30
> Can you provide more info - what program is not displaying thumnails? Nemo?
> 
> `dpkg --list | grep ffmpeg`
> 
> ffmpeg's thumbnailer should already be in use - if you start nemo from a terminal, are there any errors? (Make sure to kill it first `nemo --quit` and then start it)
> 
> If your home folder a 'new' home folder (meaning, you didn't install this to a machine with a separate home partition)?
> 
> Try deleting the cache folder (`rm -rf ~/.cache`)

it's 3gp, ogv, heif and webp formats also some don't work in the default picture program
